name: CD Docker
on:
  push:
    branches: [main]
  release:
    types: [published]
permissions:
  packages: write
jobs:
  test:
    uses: ./CI.yml
  build-latest:
    needs: test
    if: ${{ github.event_name == 'push' }}
    uses: "Recodive/Workflows/.github/workflows/CD Docker.yml@main"
    with:
      context: master/.
      tags: premid/schemas
      version: latest
    secrets:
      GH_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
  build-release:
    needs: test
    if: ${{ github.event_name == 'release' }}
    uses: "Recodive/Workflows/.github/workflows/CD Docker.yml@main"
    with:
      context: master/.
      tags: premid/schemas
      version: ${{ github.event.release.tag_name }}
    secrets:
      GH_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
