name: CI
on: [push, pull_request, workflow_call]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Lint
        run: pnpm lint
